runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGODB_URI: "your_mongodb_connection_string"
  JWT_SECRET: "your_jwt_secret"

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
